[package]
name = "harpia-render"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "GBuffer packing, MaterialGPU, IBL CPU, CSM math, meshes. No vk::*."

[dependencies]
harpia-core.workspace = true
harpia-math.workspace = true
harpia-rhi.workspace = true
gltf.workspace = true
tracing.workspace = true
