[package]
name = "harpia-ffx-spd"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "FidelityFX SPD wrapper. SPIR-V + CPU setup. No vkCmd*."

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
harpia-plugin.workspace = true

[build-dependencies]
harpia-shader-build.workspace = true
